import json
from pathlib import Path

from django.conf import settings

DIST_DIR = Path(settings.BASE_DIR) / 'static/dist'


def webpack_chunks(entrypoint, file_suffix):
    """Yield URLs of chunks to include for an `entrypoint`

    Get the list of output chunks from manifest generated by webpack.
    Guess which chunks concern this `entrypoint` from the chunk filename.
    """
    manifest_path = DIST_DIR / 'manifest.json'
    if not manifest_path.exists():
        return
    manifest_raw = manifest_path.read_text()
    manifest = json.loads(manifest_raw)
    for infile, outfile in manifest.items():
        if not outfile.endswith(file_suffix):
            continue
        fname = infile.split('.')[0]
        parts = fname.split('~')
        if entrypoint in parts:
            yield outfile


def webpack_scripts(entrypoint: str):
    yield from webpack_chunks(entrypoint, '.bundle.js')


def webpack_styles(entrypoint: str):
    yield from webpack_chunks(entrypoint, '.bundle.css')
